language: r
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

r_packages:
  - bookdown

pandoc_version: 1.19.2.1

sudo: false

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
#  - ./_deploy.sh

notifications:
  email: false

deploy:
  provider: pages               # Specify the gh-pages deployment method
  skip_cleanup: true            # Don't remove files
  local_dir: docs               # Deploy the docs folder
  github_token: $GITHUB_PAT     # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
