language: r
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

r_packages:
  - bookdown

pandoc_version: 1.19.2.1

sudo: false

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email: false
